/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_TXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_TXD_SIGNAL                                 TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_RXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_RXD_SIGNAL                                 RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

#define BOARD_INITCSI_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x040000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B1_08 (coord H13), AUD_INT/CSI_D9//J35[13]/J22[4] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D9_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D9_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D9_CHANNEL                                          9U   /*!< Signal channel */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D8_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D8_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D8_CHANNEL                                          8U   /*!< Signal channel */

/* GPIO_AD_B1_10 (coord L13), SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D7_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D7_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D7_CHANNEL                                          7U   /*!< Signal channel */

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D6_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D6_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D6_CHANNEL                                          6U   /*!< Signal channel */

/* GPIO_AD_B1_12 (coord H12), SAI1_RXD/CSI_D5/J35[5]/U13[16] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D5_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D5_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D5_CHANNEL                                          5U   /*!< Signal channel */

/* GPIO_AD_B1_13 (coord H11), SAI1_TXD/CSI_D4/J35[3]/U13[14] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D4_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D4_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D4_CHANNEL                                          4U   /*!< Signal channel */

/* GPIO_AD_B1_15 (coord J14), SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D2_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D2_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D2_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_B1_14 (coord G12), SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D3_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D3_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D3_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_AD_B1_04 (coord L12), CSI_PIXCLK/J35[8]/J23[3] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_PIXCLK_PERIPHERAL                                  CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_PIXCLK_SIGNAL                               csi_pixclk   /*!< Signal name */

/* GPIO_AD_B1_05 (coord K12), CSI_MCLK/J35[12]/J23[4] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_MCLK_PERIPHERAL                                    CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_MCLK_SIGNAL                                   csi_mclk   /*!< Signal name */

/* GPIO_AD_B1_06 (coord J12), CSI_VSYNC/J35[18]/J22[2]/UART_TX */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_VSYNC_PERIPHERAL                                   CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_VSYNC_SIGNAL                                 csi_vsync   /*!< Signal name */

/* GPIO_AD_B1_07 (coord K10), CSI_HSYNC/J35[16]/J22[1]/UART_RX */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_HSYNC_PERIPHERAL                                   CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_HSYNC_SIGNAL                                 csi_hsync   /*!< Signal name */

/* GPIO_AD_B1_00 (coord J11), I2C1_SCL/CSI_I2C_SCL/J35[20]/J23[6]/U13[17]/U32[4] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_I2C_SCL_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_I2C_SCL_SIGNAL                                     SCL   /*!< Signal name */

/* GPIO_AD_B1_01 (coord K11), I2C1_SDA/CSI_I2C_SDA/J35[22]/J23[5]/U13[18]/U32[6] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_I2C_SDA_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_I2C_SDA_SIGNAL                                     SDA   /*!< Signal name */

/* GPIO_AD_B1_02 (coord L11), CSI_PWDN */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_PWDN_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_PWDN_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITCSI_CSI_PWDN_CHANNEL                                       18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCSI_CSI_PWDN_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITCSI_CSI_PWDN_GPIO_PIN                                      18U   /*!< GPIO pin number */
#define BOARD_INITCSI_CSI_PWDN_GPIO_PIN_MASK                         (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITCSI_CSI_PWDN_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITCSI_CSI_PWDN_PIN                                           18U   /*!< PORT pin number */
#define BOARD_INITCSI_CSI_PWDN_PIN_MASK                              (1U << 18U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCSI(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
