#ifndef __THEME__
#define __THEME__

#include "font/font.h"
#include "screen/screen.h"

#define TH_DEF_LEFT_MARGIN 4

#define TH_COLOR_BG SCREEN_COLOR_BLACK
#define TH_COLOR_FG SCREEN_COLOR_WHITE
#define TH_COLOR_ACCENT SCREEN_RGB(0xff, 0x64, 0x00)
#define TH_COLOR_FIELD_BG SCREEN_RGB(37, 41, 56)
#define TH_COLOR_INACTIVE SCREEN_RGB(0xaf, 0xaf, 0xaf)
#define TH_COLOR_ERROR SCREEN_RGB(0xff, 0x00, 0x00)

#define TH_COLOR_QR_BG TH_COLOR_BG
#define TH_COLOR_QR_NOT_FOUND TH_COLOR_ERROR
#define TH_COLOR_QR_NOT_DECODED SCREEN_RGB(0xff, 0xd2, 0x33)
#define TH_COLOR_QR_OK SCREEN_RGB(0x00, 0xff, 0x00)

#define TH_COLOR_MENU_BG TH_COLOR_BG
#define TH_COLOR_MENU_FG TH_COLOR_FG
#define TH_COLOR_MENU_SELECTED_BG TH_COLOR_BG
#define TH_COLOR_MENU_SELECTED_FG TH_COLOR_ACCENT
#define TH_COLOR_MENU_MARK TH_COLOR_FG

#define TH_COLOR_SEP TH_COLOR_FG

#define TH_COLOR_TITLE_BG TH_COLOR_BG
#define TH_COLOR_TITLE_FG TH_COLOR_INACTIVE
#define TH_COLOR_TITLE_ICON_FG TH_COLOR_FG

#define TH_COLOR_LABEL_BG TH_COLOR_BG
#define TH_COLOR_LABEL_FG TH_COLOR_INACTIVE

#define TH_COLOR_DATA_BG TH_COLOR_BG
#define TH_COLOR_DATA_FG TH_COLOR_FG

#define TH_COLOR_TEXT_BG TH_COLOR_BG
#define TH_COLOR_TEXT_FG TH_COLOR_FG

#define TH_COLOR_PROGRESS_BG TH_COLOR_FIELD_BG
#define TH_COLOR_PROGRESS_FG TH_COLOR_ACCENT

#define TH_FONT_MENU &free_sans_18px
#define TH_FONT_LABEL &free_sans_18px
#define TH_FONT_DATA &plat_nomor_16px
#define TH_FONT_TITLE &free_sans_18px
#define TH_FONT_TEXT &free_sans_18px
#define TH_FONT_ICONS &icons_28px

#define TH_MENU_HEIGHT 30
#define TH_MENU_VERTICAL_MARGIN 4
#define TH_MENU_LEFT_MARGIN TH_DEF_LEFT_MARGIN
#define TH_MENU_RIGHT_MARGIN 8
#define TH_MENU_MARK_WIDTH 12
#define TH_MENU_MARK_HEIGHT 12

#define TH_SEP_HEIGHT 2

#define TH_LABEL_HEIGHT 26
#define TH_LABEL_LEFT_MARGIN TH_DEF_LEFT_MARGIN

#define TH_DATA_HEIGHT 26
#define TH_DATA_LEFT_MARGIN TH_DEF_LEFT_MARGIN

#define TH_INLINE_DATA_LEFT_MARGIN 72

#define TH_TITLE_HEIGHT 28
#define TH_TITLE_LEFT_MARGIN TH_DEF_LEFT_MARGIN
#define TH_TITLE_ICON_POSITION 280

#define TH_TEXT_HORIZONTAL_MARGIN TH_DEF_LEFT_MARGIN
#define TH_TEXT_VERTICAL_MARGIN 8

#define TH_QRCODE_VERTICAL_MARGIN 8
#define TH_QRCODE_ADDR_MARGIN 60

#define TH_PIN_FIELD_VERTICAL_MARGIN 16
#define TH_PUK_FIELD_VERTICAL_MARGIN 4

#define TH_KEYBOARD_KEY_SIZE 32
#define TH_KEYBOARD_KEY_BG TH_COLOR_BG
#define TH_KEYBOARD_KEY_SELECTED_BG TH_COLOR_ACCENT

#define TH_TEXT_FIELD_BG TH_COLOR_BG
#define TH_TEXT_FIELD_FG TH_COLOR_FG
#define TH_TEXT_FIELD_SUGGESTION_FG TH_COLOR_INACTIVE
#define TH_TEXT_FIELD_MARGIN 8
#define TH_TEXT_FIELD_HINT_MARGIN 16
#define TH_TEXT_FIELD_TOP 52
#define TH_TEXT_FIELD_HEIGHT 24
#define TH_TEXT_FIELD_CURSOR_WIDTH 2
#define TH_TEXT_FIELD_CURSOR_COLOR TH_COLOR_ACCENT

#define TH_MNEMONIC_TOP_MARGIN 8
#define TH_MNEMONIC_LEFT_MARGIN 5
#define TH_MNEMONIC_FIELD_WIDTH 100

#define TH_PROGRESS_HEIGHT 20
#define TH_PROGRESS_WIDTH 300
#define TH_PROGRESS_LEFT_MARGIN 10
#define TH_PROGRESS_VERTICAL_MARGIN 10

#define TH_NAV_HINT_LEFT_X 0
#define TH_NAV_HINT_RIGHT_X (SCREEN_WIDTH - 28)
#define TH_NAV_HINT_TOP (SCREEN_HEIGHT - 28)
#define TH_NAV_HINT_WIDTH 40
#define TH_NAV_HINT_HEIGHT 30

#endif
